CREATE TABLE servers (
  id BIGINT NOT NULL PRIMARY KEY,
  name CITEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE channels (
  id BIGINT NOT NULL PRIMARY KEY,
  name CITEXT NOT NULL,
  server_id BIGINT NOT NULL REFERENCES servers(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE members (
  id BIGINT NOT NULL PRIMARY KEY,
  name CITEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE messages (
  id BIGINT NOT NULL PRIMARY KEY,
  message TEXT NOT NULL,
  channel_id BIGINT NOT NULL REFERENCES channels(id),
  member_id BIGINT NOT NULL REFERENCES members(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE quotes (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  quote TEXT NOT NULL,
  server_id BIGINT NOT NULL REFERENCES servers(id),
  member_id BIGINT NOT NULL REFERENCES members(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE xps (
  xp INT NOT NULL DEFAULT 0,
  server_id BIGINT NOT NULL REFERENCES servers(id),
  member_id BIGINT NOT NULL REFERENCES members(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY(server_id, member_id)
);

CREATE TABLE member_aliases (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  alias CITEXT NOT NULL,
  server_id BIGINT NOT NULL REFERENCES servers(id),
  member_id BIGINT NOT NULL REFERENCES members(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT unique_alias UNIQUE(server_id, alias)
);
